# Generated by Django 5.0.3 on 2024-03-21 14:26

import Voting.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('party', models.CharField(choices=[('Umoja', 'Umoja'), ('Maendeleo', 'Maendeleo'), ('Utumishi', 'Utumishi'), ('Mfalme', 'Mfalme')], max_length=50)),
                ('position', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Finance Secretary', 'Finance Secretary'), ('Academic Secretary', 'Academic Secretary'), ('Delegate', 'Delegate')], max_length=100)),
                ('votes', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to=Voting.models.upload_location)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='UserVoteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
